netty:
  server:
    transfer:
      port: 9812
#      type: tcp
      type: websocket
      maxContentLength: 65535
      websocket:
        path: /websocket
        subProtocol: null
        allowExtensions: true
    thread:
      count:
        boss: 1
        worker: 1
    log:
      level:
        pipeline: INFO
        bootstrap: INFO
logging:
  level:
    io.netty: INFO
    com.zepinos.chat.server.ChatServerApplication: INFO
    ROOT: WARN